"""initial schema

Revision ID: 70911dfb526b
Revises: 
Create Date: 2026-08-19 17:28:36.846882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70911dfb526b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.String(), nullable=False),
    sa.Column('source_filename', sa.String(), nullable=False),
    sa.Column('checked_against_document_id', sa.String(), nullable=True),
    sa.Column('previous_version_id', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_file_path', sa.String(), nullable=True),
    sa.Column('type_metadata', sa.JSON(), nullable=True),
    sa.CheckConstraint("approval_status in ('draft','in_review','approved')", name='ck_documents_approval_status'),
    sa.CheckConstraint("doc_type in ('requirement','design','change_request')", name='ck_documents_doc_type'),
    sa.ForeignKeyConstraint(['checked_against_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'doc_type', 'version', name='uq_documents_project_type_version')
    )
    op.create_table('ai_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('call_type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("call_type in ('extraction','alignment','rerank','crop','synthesis')", name='ck_ai_calls_call_type'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alignment_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('design_document_id', sa.String(), nullable=False),
    sa.Column('requirements_document_id', sa.String(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status in ('aligned','partial','misaligned')", name='ck_alignment_reports_status'),
    sa.ForeignKeyConstraint(['design_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['requirements_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenarios', sa.JSON(), nullable=True),
    sa.Column('error_handling', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type in ('epic','story')", name='ck_requirement_items_type'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['requirement_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'external_id', name='uq_requirement_items_doc_external_id')
    )
    op.create_table('alignment_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alignment_report_id', sa.String(), nullable=False),
    sa.Column('requirement_item_id', sa.String(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('resolution_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("resolution_status in ('open','resolved','dismissed')", name='ck_alignment_findings_resolution_status'),
    sa.ForeignKeyConstraint(['alignment_report_id'], ['alignment_reports.id'], ),
    sa.ForeignKeyConstraint(['requirement_item_id'], ['requirement_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_as_item_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("severity in ('low','medium','high')", name='ck_gaps_severity'),
    sa.CheckConstraint("status in ('open','resolved','dismissed')", name='ck_gaps_status'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['resolved_as_item_id'], ['requirement_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gaps')
    op.drop_table('alignment_findings')
    op.drop_table('requirement_items')
    op.drop_table('alignment_reports')
    op.drop_table('ai_calls')
    op.drop_table('documents')
    op.drop_table('projects')
    # ### end Alembic commands ###
